import 'package:flutter/material.dart';
import 'package:hisaaber_v1/providers/auth_provider.dart';
import 'package:hisaaber_v1/providers/history_provider.dart';
import 'package:hisaaber_v1/providers/profile_provider.dart';
import 'package:hisaaber_v1/screens/splash_screen.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:google_fonts/google_fonts.dart';
import 'models/bill_item_model.dart';
import 'models/saved_bill_model.dart';
import 'models/user_profile_model.dart';
import 'firebase_options.dart';
// import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

// This file is generated by the FlutterFire CLI.
import 'providers/bill_provider.dart';

// The main entry point for the application.
void main() async {
  // --- INITIALIZATION SECTION ---

  // 1. Ensure that all Flutter bindings are initialized.
  // This is required before using platform channels (like Firebase and Hive).
  WidgetsFlutterBinding.ensureInitialized();

  // 2. Initialize Hive for local storage.
  // The 'await' keyword means we wait until this task is done before moving on.
  await Hive.initFlutter();

  Hive.registerAdapter(BillItemModelAdapter());
  Hive.registerAdapter(SavedBillModelAdapter());
  Hive.registerAdapter(UserProfileModelAdapter());

  // 3. Initialize Firebase for cloud services.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // --- RUN APP SECTION ---
  // Once all services are initialized, run the app.
  runApp(
    // 4. Use ChangeNotifierProvider/MultiProvider to make your app state available to all screens.
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => BillProvider()),
        ChangeNotifierProvider(create: (_) => HistoryProvider()),
        ChangeNotifierProvider(create: (_) => ProfileProvider()),
      ],
      child: const HisaaberApp(),
    ),
  );
}

// This is the root widget of your application.
class HisaaberApp extends StatelessWidget {
  const HisaaberApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Hisaaber',
      debugShowCheckedModeBanner: false,

      // --- THEME SECTION ---
      // Define the look and feel of your app.
      theme: ThemeData(
        // Set the background color for all screens.
        scaffoldBackgroundColor: Colors.white,

        // Set Poppins as the default font family.
        fontFamily: GoogleFonts.poppins().fontFamily,

        // Define a custom theme for the AppBar.
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          elevation: 0, // No shadow
          centerTitle: true,
          iconTheme: IconThemeData(color: Colors.black),
          titleTextStyle: TextStyle(
            color: Colors.black,
            fontSize: 22,
            fontWeight: FontWeight.w600,
          ),
        ),

        // Define a custom theme for all ElevatedButton widgets.
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF69F0AE), // Your primary green
            foregroundColor: Colors.black, // Text color
            elevation: 0,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
            textStyle: const TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.w600,
            ),
          ),
        ),
      ),

      localizationsDelegates: const [
        // AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'), // English
        Locale('hi'), // Hindi
      ],
      // Set the initial screen of the app.
      home: const SplashScreen(),
    );
  }
}
